### ISSUE TITLE
Update vertx dependency to 3.8.6

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#81] opened 2020-02-25 12:21 UTC
Wait for `3.8.6` release of vertx-core and vertx-rx to replace changes from #80 PR

**Comment by Guseyn** [comment] 2020-03-12 10:51
it's duplicate of #39

**Closed** 2020-03-12 11:43 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2020-03-12 15:30
Job `gh:artipie/asto#81` is not assigned, can't get performer
